// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLSYBOR9Uo59UkQM0ogSyKh1BAUBc1oA0',
    appId: '1:1093320347327:web:8c348370030c56ae1d000a',
    messagingSenderId: '1093320347327',
    projectId: 'bookitbookingapp',
    authDomain: 'bookitbookingapp.firebaseapp.com',
    storageBucket: 'bookitbookingapp.firebasestorage.app',
    measurementId: 'G-EPCH7ZCKJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFOkKMvNTyAfYbTw-pZLIHqCFEml-m1RY',
    appId: '1:1093320347327:android:3458669207dc6f451d000a',
    messagingSenderId: '1093320347327',
    projectId: 'bookitbookingapp',
    storageBucket: 'bookitbookingapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp0D8fnKwSCYrxih3uu4amGQiwo66qk6U',
    appId: '1:1093320347327:ios:74511a70d79878031d000a',
    messagingSenderId: '1093320347327',
    projectId: 'bookitbookingapp',
    storageBucket: 'bookitbookingapp.firebasestorage.app',
    iosBundleId: 'com.example.projectapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp0D8fnKwSCYrxih3uu4amGQiwo66qk6U',
    appId: '1:1093320347327:ios:74511a70d79878031d000a',
    messagingSenderId: '1093320347327',
    projectId: 'bookitbookingapp',
    storageBucket: 'bookitbookingapp.firebasestorage.app',
    iosBundleId: 'com.example.projectapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLSYBOR9Uo59UkQM0ogSyKh1BAUBc1oA0',
    appId: '1:1093320347327:web:06af7d7bdf9dce941d000a',
    messagingSenderId: '1093320347327',
    projectId: 'bookitbookingapp',
    authDomain: 'bookitbookingapp.firebaseapp.com',
    storageBucket: 'bookitbookingapp.firebasestorage.app',
    measurementId: 'G-LZWSJSMJZV',
  );
}
